/**
 * @file events-desktop-page.tsx
 * @description Desktop events page rendered from the provided reference layout.
 * @module frontend/src/pages/desktop
 */

import { StaticMarkupPage } from "../../components/ui/static-markup-page";

const html = String.raw`
<div class="relative flex h-auto min-h-screen w-full flex-col overflow-x-hidden bg-background-light text-slate-900">
  <div class="layout-container flex h-full grow flex-col">
    <header class="flex items-center justify-between whitespace-nowrap border-b border-solid border-primary/10 px-6 md:px-20 py-4 bg-background-light/80 backdrop-blur-md sticky top-0 z-50">
      <div class="flex items-center gap-8"><div class="flex items-center gap-3 text-primary"><div class="size-8 flex items-center justify-center bg-primary text-white rounded-lg"><span class="material-symbols-outlined text-xl!">eco</span></div><h2 class="text-slate-900 text-xl font-bold leading-tight tracking-tight">Krutha Foundation</h2></div><nav class="hidden lg:flex items-center gap-8"><a class="text-slate-600 hover:text-primary text-sm font-medium transition-colors" href="/">Home</a><a class="text-slate-600 hover:text-primary text-sm font-medium transition-colors" href="/our-work">Projects</a><a class="text-primary text-sm font-bold border-b-2 border-primary" href="/events">Events</a><a class="text-slate-600 hover:text-primary text-sm font-medium transition-colors" href="/about">About</a><a class="bg-primary text-white px-5 py-2 rounded-full text-sm font-bold hover:bg-primary/90 transition-all" href="/contact">Donate</a></nav></div>
      <div class="flex items-center gap-6"><label class="hidden md:flex items-center bg-primary/5 rounded-full px-4 py-2 border border-primary/10 focus-within:border-primary transition-all"><span class="material-symbols-outlined text-slate-400 mr-2 text-xl">search</span><input class="bg-transparent border-none focus:ring-0 text-sm w-48 placeholder-slate-400" placeholder="Search events..." type="text" /></label><div class="size-10 rounded-full bg-primary/20 flex items-center justify-center text-primary overflow-hidden"><img class="w-full h-full object-cover" src="https://lh3.googleusercontent.com/aida-public/AB6AXuAChjSZ7b-QBKv48WjPvZ3SkIPFdVNu89s3OoVCEvRA4yeGW9LWEAaPS-iD7ivaeeAuF0EsRg-B8uDUFFw3L0dZ-XegF71mAGgUmk44cJnX0Edgb3GWT0UnX3p5mItj2tlVcu9UEPMf1Tc1zuj9esDLFO1f_44EJJgvSmjtFZ1n_PX9OFHlEdOze5bnwPD72hU1jj9IjdBoMhvuUstagJ10zQ88C1nSKuFG0W_X5HLrMYy7zwhtfcBSGJYmoV5aG0iDk1K8080PihM-" alt="User profile avatar" /></div></div>
    </header>
    <main class="max-w-7xl mx-auto w-full px-6 md:px-20 py-12"><div class="mb-12"><h1 class="text-4xl md:text-5xl font-black text-slate-900 mb-4 tracking-tight">Impact in Action</h1><p class="text-lg text-slate-600 max-w-2xl leading-relaxed">Discover our upcoming initiatives and look back at the milestones we've achieved together across rural communities.</p></div><div class="flex flex-col md:flex-row md:items-center justify-between gap-6 border-b border-primary/10 pb-2 mb-10"><div class="flex gap-10"><button class="relative pb-4 text-primary font-bold text-sm tracking-wide after:content-[''] after:absolute after:bottom-0 after:left-0 after:w-full after:h-1 after:bg-primary after:rounded-t-full">UPCOMING EVENTS</button><button class="relative pb-4 text-slate-400 font-bold text-sm tracking-wide hover:text-slate-600 transition-colors">PAST EVENTS</button></div><div class="flex gap-3 overflow-x-auto pb-4 md:pb-0 no-scrollbar"><button class="px-5 py-1.5 rounded-full bg-primary text-white text-sm font-medium">All Topics</button><button class="px-5 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium hover:bg-primary/20 transition-colors">Community</button><button class="px-5 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium hover:bg-primary/20 transition-colors">Environment</button><button class="px-5 py-1.5 rounded-full bg-primary/10 text-primary text-sm font-medium hover:bg-primary/20 transition-colors">Education</button></div></div>
      <section class="mb-16"><div class="group relative flex flex-col lg:flex-row bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition-shadow duration-300 border border-primary/5"><div class="lg:w-3/5 h-[300px] lg:h-auto overflow-hidden relative"><img class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBSwK97pwjcXde2gwIszrKbU-ofaWI79VMlBQu_timTiLJEa7f6nU2ZI4j-SicFNH7ZINUMePlsvjoNYr7uAWeRdw7RdLo51mZ0Kw8yrMIjaQOby-UWgZnhYR3aUlcuXZ2qSu7ao4fEga3_iocgU49D6opd7HiqKqhVmZwdBuKhwZjM30bYKs9oGIQMkI8qM4w9Ln-qPsVcuSoL85TnGnLIQBgyZak_qRCl4scs0X_CmDDjrk5NRF0OTYBvcKYMnqmeVh-p9imVNc5s" alt="Group of villagers participating in a community sports event" /><div class="absolute top-6 left-6 bg-white/90 backdrop-blur px-4 py-2 rounded-xl shadow-lg flex items-center gap-3"><span class="material-symbols-outlined text-primary">calendar_today</span><div class="flex flex-col"><span class="text-xs font-bold text-slate-500 uppercase tracking-wider">Oct 15, 2023</span><span class="text-sm font-black text-primary">SAVE THE DATE</span></div></div></div><div class="lg:w-2/5 p-8 lg:p-12 flex flex-col justify-center"><span class="inline-block px-3 py-1 bg-primary/10 text-primary text-xs font-bold uppercase tracking-widest rounded-full mb-6 w-fit">Featured Event</span><h2 class="text-3xl font-serif font-bold text-slate-900 mb-4 leading-tight">Annual Village Sports Meet 2023</h2><p class="text-slate-600 mb-8 leading-relaxed text-lg">Celebrating local talent and sportsmanship in the heart of our villages. Join us for a day of athletic excellence, community bonding, and traditional local games.</p><div class="flex items-center gap-4"><a class="bg-primary text-white px-8 py-3 rounded-xl font-bold hover:shadow-lg transition-all active:scale-95" href="/contact">Register Now</a><a class="text-primary font-bold hover:underline flex items-center gap-2" href="/blog">Event Details <span class="material-symbols-outlined text-sm">arrow_forward</span></a></div></div></div></section>
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
        <div class="flex flex-col bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-lg transition-all border border-primary/5 group"><div class="h-60 overflow-hidden relative"><img class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCrq1s--eK9RZ69F40OY4DNo0p0Zw13QPSKCQJaH-S34wIhVuEf5ZendJ8Gug06left6eenvWhMNcOmgRsGn1W7RWtdVvv3M4PdEd97Zh5IN7so0OjlfBFwEMgiv98nAbZ111Jy54dRRVSIHeQ9xGNTjL79Sit6wfEa4JwguR29ZHnMFkwvG3rdJ4bHFraulW4YzFxxCnwjXE7-zKvBnX5JtqBvnmcW4b8-vB5vGQ1c3EOes7tCk2BBRbMFG8auiCycWGCLxce9Pv7Q" alt="Hands planting a small green tree sapling in soil" /><span class="absolute top-4 right-4 bg-primary text-white px-3 py-1 rounded-full text-xs font-bold shadow-md">Environment</span></div><div class="p-8 flex flex-col grow"><div class="flex items-center gap-2 text-slate-400 text-sm font-medium mb-3"><span class="material-symbols-outlined text-base">event</span>Nov 02, 2023 • 09:00 AM</div><h3 class="text-2xl font-serif font-bold text-slate-900 mb-4 leading-tight group-hover:text-primary transition-colors">Water Conservation Workshop</h3><p class="text-slate-600 text-sm leading-relaxed mb-6">Learn modern rainwater harvesting techniques and sustainable water management practices for small-scale rural farming.</p><div class="mt-auto pt-6 border-t border-primary/5"><a class="text-primary font-bold flex items-center gap-2" href="/blog">Read More <span class="material-symbols-outlined transition-transform">arrow_forward</span></a></div></div></div>
        <div class="flex flex-col bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-lg transition-all border border-primary/5 group"><div class="h-60 overflow-hidden relative"><img class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" src="https://lh3.googleusercontent.com/aida-public/AB6AXuBI_Z4RoHNLKWhZTPlyUREtr9FFzW6hZGxaXzBvwJAh3iewBBDfuIaNcZ9c4w8qC12RIMNMyFzv1cIshwt1qTEK8iS7767z247LLS85XWdLIKOz6nQwbcvdSJ7V3ZdPkoNra773eXpwMYqfj4q-7V2xI59Cl1BC9-m7X5iDGTq0XGq3NHRfDxxJu5Bu7ASZKCYrjMVr7GQu4qcKtvpDQEVLRV8Nrafwt-s4auGVxz1DhPu4EgTxiCl9lF3Y9oiF3y1NjBH8rJdsrCnQ" alt="Children in school uniforms receiving books and scholarships" /><span class="absolute top-4 right-4 bg-primary text-white px-3 py-1 rounded-full text-xs font-bold shadow-md">Education</span></div><div class="p-8 flex flex-col grow"><div class="flex items-center gap-2 text-slate-400 text-sm font-medium mb-3"><span class="material-symbols-outlined text-base">event</span>Dec 12, 2023 • 10:30 AM</div><h3 class="text-2xl font-serif font-bold text-slate-900 mb-4 leading-tight group-hover:text-primary transition-colors">L.E.A.D.S. Scholarship Distribution</h3><p class="text-slate-600 text-sm leading-relaxed mb-6">Supporting the bright futures of 50 deserving students through our annual scholarship distribution ceremony.</p><div class="mt-auto pt-6 border-t border-primary/5"><a class="text-primary font-bold flex items-center gap-2" href="/blog">Read More <span class="material-symbols-outlined transition-transform">arrow_forward</span></a></div></div></div>
        <div class="flex flex-col bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-lg transition-all border border-primary/5 group"><div class="h-60 overflow-hidden relative"><img class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-500" src="https://lh3.googleusercontent.com/aida-public/AB6AXuCCAiHiF2XquOblyKJ4XrTSGE7WQSZ6E9VvgXYXHepsajChWfThFcnB2k3QCEJ329W6ligtsyyAi_eRx-VoPCtb4IMlW4fhLJHLPTWcNLi7KyKKunhqQ8vcEWk0Y7b3Q4kRygjF3E780GqKUQEyGrKjXp-8nvnqH3oIyjBX0bruu4719jbePfM6_Dw8Oe7q79OsuFaPE1czKjkOP8F-M1_TdVJ0BOVOHOGyRo_yMnkiI-rcPnB-vR8hgYH2cXEXD45qrpN_kW5uakUF" alt="Close up of a village meeting with several people listening intently" /><span class="absolute top-4 right-4 bg-primary text-white px-3 py-1 rounded-full text-xs font-bold shadow-md">Community</span></div><div class="p-8 flex flex-col grow"><div class="flex items-center gap-2 text-slate-400 text-sm font-medium mb-3"><span class="material-symbols-outlined text-base">event</span>Jan 05, 2024 • 04:00 PM</div><h3 class="text-2xl font-serif font-bold text-slate-900 mb-4 leading-tight group-hover:text-primary transition-colors">Rural Entrepreneurs Conclave</h3><p class="text-slate-600 text-sm leading-relaxed mb-6">A platform for local artisans and farmers to connect with mentors and scale their micro-businesses.</p><div class="mt-auto pt-6 border-t border-primary/5"><a class="text-primary font-bold flex items-center gap-2" href="/blog">Read More <span class="material-symbols-outlined transition-transform">arrow_forward</span></a></div></div></div>
      </div><div class="flex justify-center mt-16"><a class="px-10 py-4 border-2 border-primary text-primary font-bold rounded-xl hover:bg-primary hover:text-white transition-all" href="/press">View Past Events</a></div>
    </main>
    <section class="bg-primary/5 border-y border-primary/10 py-16 px-6"><div class="max-w-4xl mx-auto text-center"><span class="material-symbols-outlined text-5xl text-primary mb-6">mail</span><h2 class="text-3xl font-serif font-bold text-slate-900 mb-4">Stay updated with our events</h2><p class="text-slate-600 mb-8">Get monthly notifications about new projects, volunteering opportunities, and foundation milestones.</p><div class="flex flex-col sm:flex-row gap-3 max-w-lg mx-auto"><input class="flex-1 px-6 py-4 rounded-xl border border-primary/20 focus:ring-primary focus:border-primary" placeholder="Your email address" type="email" /><button class="bg-primary text-white px-8 py-4 rounded-xl font-bold shadow-lg hover:bg-primary/90 transition-all">Subscribe</button></div></div></section>
    <footer class="bg-slate-900 text-slate-300 py-16 px-6 md:px-20"><div class="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-4 gap-12"><div class="col-span-1 md:col-span-2"><div class="flex items-center gap-3 text-white mb-6"><div class="size-8 flex items-center justify-center bg-primary text-white rounded-lg"><span class="material-symbols-outlined text-xl!">eco</span></div><h2 class="text-xl font-bold">Krutha Foundation</h2></div><p class="text-slate-400 max-w-sm mb-6 leading-relaxed">Empowering rural communities through sustainable development, education, and social awareness initiatives.</p><div class="flex gap-4"><a class="size-10 bg-slate-800 rounded-full flex items-center justify-center hover:bg-primary transition-colors" href="/press"><span class="material-symbols-outlined text-xl!">public</span></a><a class="size-10 bg-slate-800 rounded-full flex items-center justify-center hover:bg-primary transition-colors" href="/contact"><span class="material-symbols-outlined text-xl!">group</span></a><a class="size-10 bg-slate-800 rounded-full flex items-center justify-center hover:bg-primary transition-colors" href="/contact"><span class="material-symbols-outlined text-xl!">mail</span></a></div></div><div><h4 class="text-white font-bold mb-6 tracking-wide uppercase text-sm">Organization</h4><ul class="space-y-4"><li><a class="hover:text-white transition-colors" href="/about">Our Story</a></li><li><a class="hover:text-white transition-colors" href="/press">Impact Reports</a></li><li><a class="hover:text-white transition-colors" href="/press">Financials</a></li><li><a class="hover:text-white transition-colors" href="/contact">Careers</a></li></ul></div><div><h4 class="text-white font-bold mb-6 tracking-wide uppercase text-sm">Contact Us</h4><ul class="space-y-4 text-slate-400"><li class="flex items-start gap-3"><span class="material-symbols-outlined text-primary">location_on</span>123 Rural Link Road, Bangalore, KA 560001</li><li class="flex items-center gap-3"><span class="material-symbols-outlined text-primary">call</span>+91 80 4567 8900</li><li class="flex items-center gap-3"><span class="material-symbols-outlined text-primary">mail</span>hello@kruthafoundation.org</li></ul></div></div><div class="max-w-7xl mx-auto border-t border-slate-800 mt-16 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-sm text-slate-500"><p>(c) 2023 Krutha Foundation. All rights reserved.</p><div class="flex gap-8"><a class="hover:text-slate-300 transition-colors" href="/contact">Privacy Policy</a><a class="hover:text-slate-300 transition-colors" href="/contact">Terms of Service</a></div></div></footer>
  </div>
</div>`;

export function EventsDesktopPage() {
  return <StaticMarkupPage html={html} />;
}